ELEMENT_ALL = -2
ELEMENT_NONE = -1
ELEMENT_FIRE = 0
ELEMENT_ICE = 1
ELEMENT_ELECTRICITY = 2


-- Combat actions
COMBAT_WAITING = 0
COMBAT_DECIDING = 1
COMBAT_DEAD = 2
COMBAT_ATTACKING = 3
COMBAT_USING = 4
COMBAT_CASTING = 5
COMBAT_RUNNING = 6
COMBAT_DEFENDING = 7
COMBAT_BUSY = 8
COMBAT_SKIP = 9


-- Which side of the screen
LOCATION_LEFT = 0
LOCATION_RIGHT = 1

COMBATENTITY_TYPE_PLAYER = 0
COMBATENTITY_TYPE_ENEMY = 1
COMBATENTITY_TYPE_FRILL = 2

