FLAGS=-I/Users/trent/code/local/include -arch i386 -arch x86_64 -DMONSTER2
LINKOPTS=-L.

all: lib

lib: tgui.o
	ar rc libtgui.a tgui.o
	ranlib libtgui.a

tgui.o: tgui.cpp tgui.hpp
	g++ $(FLAGS) -c tgui.cpp -o tgui.o

clean:
	rm -f libtgui.a *.o
