FLAGS=-I/Users/trent/code/android-toolchain/user/armeabi/include
CXX=arm-linux-androideabi-g++
AR=arm-linux-androideabi-ar
RANLIB=arm-linux-androideabi-ranlib

all: lib

lib: tgui.o
	$(AR) rc libtgui.a tgui.o
	$(RANLIB) libtgui.a

tgui.o: tgui.cpp tgui.hpp
	$(CXX) $(FLAGS) -c tgui.cpp -o tgui.o

clean:
	rm -f libtgui.a *.o
