#ifndef NO_GAMECENTER

#include <allegro5/allegro.h>
#import <GameKit/GameKit.h>
#include "mygamecentervc.h"
#include "gamecenter.h"

extern ALLEGRO_DISPLAY *display;

#ifdef ALLEGRO_IPHONE
extern volatile bool modalViewShowing;
UIWindow *al_iphone_get_window(ALLEGRO_DISPLAY *display);

@implementation MyGameCenterVC

- (id)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil
{
    self = [super initWithNibName:nibNameOrNil bundle:nibBundleOrNil];
    if (self) {
        // Custom initialization
    }
    return self;
}

- (void)dealloc
{
    [super dealloc];
}

- (void)didReceiveMemoryWarning
{
    // Releases the view if it doesn't have a superview.
    [super didReceiveMemoryWarning];
    
    // Release any cached data, images, etc that aren't in use.
}

#pragma mark - View lifecycle


// Implement loadView to create a view hierarchy programmatically, without using a nib.
- (void)loadView
{
	self.wantsFullScreenLayout = YES;

	UIScreen *screen = [UIScreen mainScreen];
		
	self.view = [[UIView alloc] initWithFrame:[screen bounds]];
}


- (void)viewDidUnload
{
    [super viewDidUnload];
    // Release any retained subviews of the main view.
    // e.g. self.myOutlet = nil;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation
{
    // Return YES for supported orientations
    return (interfaceOrientation == UIInterfaceOrientationLandscapeRight) || (interfaceOrientation == UIInterfaceOrientationLandscapeLeft);
}

- (void) showAchievements
{
	GKAchievementViewController *achievements = [[GKAchievementViewController alloc] init];
	if (achievements != nil)
	{
		achievements.achievementDelegate = self;
		UIWindow *window = al_iphone_get_window(display);
		[window addSubview:self.view];
		[self presentModalViewController:achievements animated:NO];
		[window bringSubviewToFront:achievements.view];
		modalViewShowing = true;
	}
	[achievements release];
}

- (void)achievementViewControllerDidFinish:(GKAchievementViewController *)viewController
{
	[self dismissModalViewControllerAnimated:YES];
	modalViewShowing = false;
}

@end


@implementation MyUIAlertViewDelegate  

-(void)alertView:(UIAlertView *)alertView clickedButtonAtIndex:(NSInteger)buttonIndex  
{  
	result = buttonIndex;  
}  

-(int)getResult  
{  
	return result;  
}  

@end;  

int CreateModalDialog(NSString *title,  
                      NSString *msg,   
                      NSString *ok,   
                      NSString *cancel)  
{  
	// Create an instance of a custom UIAlertViewDelegate that we use to capture  
	// the events generated by the UIAlertView  
	MyUIAlertViewDelegate *lpDelegate = [[MyUIAlertViewDelegate alloc] init];  
	
	// Construct and "show" the UIAlertView (message, title, cancel, ok are all  
	// NSString values created earlier in your code...)  
	UIAlertView *lpAlertView = [[UIAlertView alloc]   
				    initWithTitle:title   
				    message:msg   
				    delegate:lpDelegate   
				    cancelButtonTitle:cancel  
				    otherButtonTitles:ok, nil];  
	
	[lpAlertView performSelectorOnMainThread: @selector(show) withObject:nil waitUntilDone:YES];  

	// By the time this loop terminates, our delegate will have been   
	// called and we can get the result from the delegate (i.e. what button was pressed...)  
	while ((!lpAlertView.hidden) && (lpAlertView.superview!=nil))  
	{  
		al_rest(0.001);
	}  
	
	// Grab the result from our delegate (via a custom property)  
	int nResult = [lpDelegate getResult];  
	
	// Tidy up!  
	[lpAlertView release];  
	[lpDelegate release];  
	
	//NSLog(@"Result: %d", nResult);  
	
	return nResult;  
}

#else

#define NOTIF_NAME @"GKDialogControllerWillDisappear"

extern NSWindow *al_osx_get_window(ALLEGRO_DISPLAY *);

@implementation MyGameCenterVC

- (void) showAchievements
{
	[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(shut_r_down:) name:NOTIF_NAME object:nil];

	GKAchievementViewController *achievements = [[GKAchievementViewController alloc] init];

	if (achievements != nil)
	{
		achievements.achievementDelegate = self;
		GKDialogController *sdc = [GKDialogController sharedDialogController];
		sdc.parentWindow = al_osx_get_window(display);
		[sdc presentViewController: achievements];
	}

	[achievements release];
}

- (void)shut_r_down:(NSNotification *)notification
{
	[[NSNotificationCenter defaultCenter] removeObserver:self name:NOTIF_NAME object:nil];

	modalViewShowing = false;
}

- (void)achievementViewControllerDidFinish:(GKGameCenterViewController *)achievementViewController
{
	GKDialogController *sdc = [GKDialogController sharedDialogController];
	[sdc dismiss: achievementViewController];
	modalViewShowing = false;
}

@end

#endif

#endif // NO_GAMECENTER
